# User-input commands
START_MEASURING_DATA = 1
PAUSE_MEASURING_DATA = 2
CLEAR_DATA = 3
EDIT_SETTINGS = 4
VIEW_WAVEFORM_DATA = 5
VIEW_POSITION_DATA = 6
VIEW_INTENSITY_DATA = 7
VIEW_POWER_DATA = 8
CLOSE_WINDOWS = 9
EXIT = 10

# Internal commands
UPDATE_PLOT = 11
